### PR TITLE
Add doughnut indicators to pipeline chart

### PR DESCRIPTION
**Pull request by tingaloo**
#64 

Looks something like so, uses svg doughnuts as status indicators. 

screen shot 2018-10-28 at 15 51 19

### CODE REVIEW

**Comment by tingaloo** [comment]
@chandankumar4 hey, sorry i'm not really sure how to do that because i'm using a circle SVG without additional libraries. And this requires some really tricky offsetting that i'm not experienced with.

**Comment by chandankumar4** [comment]
You can get help from here https://github.com/chandankumar4/ci-e2e-dashboard/tree/Add-graph
but make sure website not slow due to graph

**Comment by chandankumar4** [comment]
Can you modify with circle that will make increase a quality of circle a little bit or looks better form previous one

**Comment by tingaloo** [comment]
@chandankumar4 by quality, do you mean the radius? I don't follow what you mean.

**Comment by chandankumar4** [comment]
@tingaloo Can you make the circle like the image i have given in issue for this and increase the radius of circle an little bit more

**Comment by tingaloo** [comment]
Updated.

screen shot 2018-10-31 at 18 27 35

**Comment by tingaloo** [comment]
@chandankumar4 i keep getting conflicts even after rebasing, is 2 commits fine?

**Comment by chandankumar4** [comment]
Okay! fine

**Comment by chandankumar4** [comment]
@tingaloo  Please rebase your code once again!

**Comment by chandankumar4** [comment]
@tingaloo try to merge all three commit into one

**Pull request merged**
